import Head from 'next/head'
import "bootstrap/dist/css/bootstrap.min.css";
import axios from "axios"
import styles from '../styles/Home.module.css'
import List from '../components/List';
import {useRouter} from 'next/router';
import Cards from '../components/Card';

export default function Category({movies}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-dark">
        <h1 className="text-center text-white p-5">Movie App</h1>
        <div className="row">
          <div className="col-3 bg-dark">
            <List/>
          </div>
          <div className="col-9 bg-dark">
              <Cards movies={movies}/>
          </div>
        </div>
      </main>

    </div>
  )
}

export const getServerSideProps=async (context) => {
  const title = context.params.category
  const response = await axios(`http://www.omdbapi.com/?s=${title}&apikey=ecad4790`)

  if(!response.data) {
    return <h1>Loading...</h1>
  }
  
  // if(!response.data) {
  //   return {
  //     notFound:true
  //   }
  // }

  return {
    props: {
      movies:response.data.Search
    }
  }
}