import Head from 'next/head'
import "bootstrap/dist/css/bootstrap.min.css";
import axios from "axios"
import styles from '../styles/Home.module.css'
import List from '../components/List';
import Card from '../components/Card';

export default function Home({movies}) {
  console.log(movies,"props");
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 className="text-center text-white p-5">Movie App</h1>
        <div className="row">
          <div className="col-3">
            <List/>
          </div>
          <div className="col-9 bg-dark">
            <Card movies={movies} />
          </div>
        </div>
      </main>

    </div>
  )
}

export const getServerSideProps= async(context) => {
  const response = await axios("http://www.omdbapi.com/?s=movie&apikey=ecad4790")

  if(!response.data) {
    return {
      notFound:true
    }
  }
  return {
    props: {
      movies:response.data.Search
    }
  }
}